### ISSUE TITLE
Cannot read property 'TR' of undefined

### ISSUE THREAD

**Issue by awmiklovic** [enzymejs/enzyme#2381]
### Current behavior

Dependency Cheerio throws error when setting up enzyme. 

    TypeError: Cannot read property 'TR' of undefined

    > 7 | import { configure } from 'enzyme';
        | ^

### Expected behavior
No errors.

### Your environment
Reproducible with clean install of create-react-app --typescript and following basic enzyme setup per docs.

Node version: v12.16.2

#### Version

| library             | version
| ------------------- | -------
| enzyme              |  3.11.0
| react               | 16.13.1
| react-dom           | 16.13.1
| react-test-renderer | 16.13.1
| adapter (below)     | 1.15.2

#### Adapter

- [ x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
I'm not sure why an import statement would be erroring on a `TR` property. Can you share the entire file, as well as the entire stack trace?

**Comment by awmiklovic** [comment]
setupTests.js
`import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
configure({ adapter: new Adapter() });
`
Stack trace
` FAIL  src/__tests__/test.tsx
  ● Test suite failed to run

    TypeError: Cannot read property 'TR' of undefined

    > 1 | import { configure } from 'enzyme';
        | ^
      2 | import Adapter from 'enzyme-adapter-react-16';
      3 | configure({ adapter: new Adapter() });
      4 | 

      at Object.<anonymous> (node_modules/cheerio/node_modules/parse5/lib/parser/index.js:58:28)
      at Object.<anonymous> (node_modules/cheerio/node_modules/parse5/lib/index.js:3:14)
      at Object.<anonymous> (node_modules/cheerio/lib/parse.js:5:14)
      at Object.<anonymous> (node_modules/cheerio/lib/cheerio.js:5:13)
      at Object.<anonymous> (node_modules/cheerio/index.js:5:28)
      at Object.<anonymous> (node_modules/enzyme/src/Utils.js:9:1)
      at Object.<anonymous> (node_modules/enzyme/src/ReactWrapper.js:4:1)
      at Object.<anonymous> (node_modules/enzyme/src/index.js:1:1)
      at Object.<anonymous> (src/setupTests.js:1:1)
          at Array.forEach (<anonymous>)

  console.log node_modules/common/lib/logging.js:18
    using API root:  https://staging.modernanimal.com/v1/

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.156s
Ran all test suites related to changed files.

Watch Usage: Press w to show more.`

**Comment by awmiklovic** [comment]
Figured it out!

**Comment by ljharb** [comment]
Great! What was the problem?

**Comment by awmiklovic** [comment]
The issue seems to be the config for a package that I use in my project. The package has both uncompiled typescript and compiled typescript at the root level so I'm trying to map the module to use index.js instead of index.ts in the Jest config.

Adding this to the config fixed my Jest issues, but when I added enzyme I started getting the "Cannot read property 'TR' of undefined" error. I'm far from actually figuring what the problem is or how to fix, but it doesn't seem to be a problem with Enzyme's base install as suggested.\

```
  "jest": {
    "moduleNameMapper": {
      "^react-native$": "react-native-web",
      "^.+\\.module\\.(css|sass|scss)$": "identity-obj-proxy",
      "common": "<rootDir>/node_modules/common/index.js".     <= This package here
    }
  }
```

setupFiles.js
```
import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
configure({ adapter: new Adapter() });
```

Stack trace
```
 FAIL  src/__tests__/test.tsx
  ● Test suite failed to run

    TypeError: Cannot read property 'TR' of undefined

    > 1 | import { configure } from 'enzyme';
        | ^
      2 | import Adapter from 'enzyme-adapter-react-16';
      3 | configure({ adapter: new Adapter() });
      4 | 

      at Object.<anonymous> (node_modules/cheerio/node_modules/parse5/lib/parser/index.js:58:28)
      at Object.<anonymous> (node_modules/cheerio/node_modules/parse5/lib/index.js:3:14)
      at Object.<anonymous> (node_modules/cheerio/lib/parse.js:5:14)
      at Object.<anonymous> (node_modules/cheerio/lib/cheerio.js:5:13)
      at Object.<anonymous> (node_modules/cheerio/index.js:5:28)
      at Object.<anonymous> (node_modules/enzyme/src/Utils.js:9:1)
      at Object.<anonymous> (node_modules/enzyme/src/ReactWrapper.js:4:1)
      at Object.<anonymous> (node_modules/enzyme/src/index.js:1:1)
      at Object.<anonymous> (src/setupTests.js:1:1)
          at Array.forEach (<anonymous>)

  console.log node_modules/common/lib/logging.js:18
    using API root:  https://[redacted].com/v1/
```
