### ISSUE TITLE
测试umi页面报错： (0 , _umi.connect) is not a function, 试了很多方案无法解决

### ISSUE THREAD

**Issue by zhangxiangqiang** [enzymejs/enzyme#2432]
umi项目，当我用enzyme 进行单元测试时，引入了使用umi.connect 包裹的组件，会报错，无法进行测试

组件是用react hooks 纯函数写的，这是测试代码，最简单的挂载跑不通
```jsx
import React from 'react';
import { shallow, configure, mount } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
import { matchMedia } from '@/utils/utilsTest';
import workbench from './index';

configure({ adapter: new Adapter() });
console.log(workbench, 999)
beforeAll(() => {
matchMedia();
});

describe('', () => {
it('渲染基本UI', () => {
const $ = shallow();
expect($.find('Select').length).toBe(1);
});
});
```
下面是组件写法：
```jsx
export interface WorkbenchProps extends ConnectProps {
  dispatch: Dispatch;
  workbench: WorkBenchState;
  loadingDetail: boolean | undefined;
}

...
};

export default connect(({ workbench, loading }: ConnectState & WorkbenchProps) => ({
  workbench,
  loadingDetail: loading.effects[API.query],
}))(Workbench);
```

下面是错误日志：
```sh
TypeError: (0 , _umi.connect) is not a function

  218 | };
  219 | 
> 220 | export default connect(({ workbench, loading }: ConnectState & WorkbenchProps) => ({
      |                ^
  221 |   workbench,
  222 |   loadingDetail: loading.effects[API.query],
  223 | }))(Workbench);

  at Object.<anonymous> (src/pages/kms/workbench/index.tsx:220:16)
  at Object.<anonymous> (src/pages/kms/workbench/index.test.ts:5:1)
```
相关环境信息：
Umi 版本：^3.2.9
Node 版本：v12.18.1
操作系统：mac OS

**Comment by ljharb** [comment]
Hi - I'm not familiar with umi, nor what "umi.connect" is.

Please do fill out the entire issue template - it's there for a reason.

However, this looks like an issue with your code itself - `connect` isn't a function in your actual component code. Closing for now, but will be happy to reopen if you fill out the issue template and it turns out there's something actionable related to enzyme here.
