### ISSUE TITLE
React is not defined (Typescript)

### ISSUE THREAD

**Issue by delucca** [enzymejs/enzyme#2478]
Hi!

I'm facing an issue with a simple test I'm trying to write with Enzyme.
**IMPORTANT:** I'm not using React 17 yet. We're using `16.14.0`

Here is the test I'm trying to implement:

```tsx
import faker from 'faker'
import React from 'react'
import enzyme from 'enzyme'
import Wallet from './wallet'

describe('props rendering', () => {
  it('renders provided title as svg title', () => {
    const fakeTitle = faker.random.word()
    const wallet = enzyme.shallow(<Wallet title={fakeTitle} desc={''} />)

    const svgTitleComponent = wallet.find('title')

    expect(svgTitleComponent.children()).toEqual(fakeTitle)
  })
})
```

And here is the component:
```tsx
import { Icon, IconProps } from '@chakra-ui/react'
import React, { ReactElement } from 'react'

import { AcessibleIconProperties } from 'src/components/Icons/types'

export interface WalletIconProperties extends IconProps, AcessibleIconProperties {}

const Wallet = ({ title, desc, ...rest }: WalletIconProperties): ReactElement => (
  <Icon viewBox="0 0 24 24" {...rest}>
    <title>{title}</title>
    <desc>{desc}</desc>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M21.9964 8.37513H17.7618C15.7911 8.37859 14.1947 9.93514 14.1911 11.8566C14.1884 13.7823 15.7867 15.3458 17.7618 15.3484H22V15.6543C22 19.0136 19.9636 21 16.5173 21H7.48356C4.03644 21 2 19.0136 2 15.6543V8.33786C2 4.97862 4.03644 3 7.48356 3H16.5138C19.96 3 21.9964 4.97862 21.9964 8.33786V8.37513ZM6.73956 8.36733H12.3796H12.3831H12.3902C12.8124 8.36559 13.1538 8.03019 13.152 7.61765C13.1502 7.20598 12.8053 6.87318 12.3831 6.87491H6.73956C6.32 6.87664 5.97956 7.20858 5.97778 7.61852C5.976 8.03019 6.31733 8.36559 6.73956 8.36733Z"
    />
    <path
      opacity="0.4"
      d="M16.0374 12.2967C16.2465 13.2479 17.0805 13.9171 18.0326 13.8997H21.2825C21.6787 13.8997 22 13.5716 22 13.166V10.6345C21.9991 10.2298 21.6787 9.90087 21.2825 9.9H17.9561C16.8731 9.90348 15.9983 10.8024 16 11.9103C16 12.0399 16.0128 12.1696 16.0374 12.2967"
    />
    <circle cx="18" cy="11.9" r="1" />
  </Icon>
)

Wallet.defaultProps = {
  fill: 'black',
}

export default Wallet
```

After running the test, I got the following output (Jest):
```
 FAIL  src/components/Icons/Wallet/wallet.spec.tsx
  ● props rendering › renders provided title as svg title

    ReferenceError: React is not defined

       7 |   it('renders provided title as svg title', () => {
       8 |     const fakeTitle = faker.random.word()
    >  9 |     const wallet = enzyme.shallow(<Wallet title={fakeTitle} desc={''} />)
         |                                   ^
      10 |
      11 |     const svgTitleComponent = wallet.find('title')
      12 |

      at Object.<anonymous> (src/components/Icons/Wallet/wallet.spec.tsx:9:35)
```

And, if I change my react import statement in the test to:
```tsx
import * as React from 'react'
```

The error now is:
```
 FAIL  src/components/Icons/Wallet/wallet.spec.tsx (5.542 s)
  ● props rendering › renders provided title as svg title

    ReferenceError: React is not defined

       6 | export interface WalletIconProperties extends IconProps, AcessibleIconProperties {}
       7 |
    >  8 | const Wallet = ({ title, desc, ...rest }: WalletIconProperties): ReactElement => (
         |                                                                                  ^
       9 |   <Icon viewBox="0 0 24 24" {...rest}>
      10 |     <title>{title}</title>
      11 |     <desc>{desc}</desc>

      at Wallet (src/components/Icons/Wallet/wallet.tsx:8:82)
      at Wallet (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:619:42)
      at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:829:32)
      at renderElement (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:642:26)
      at fn (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:704:46)
      at withSetStateAllowed (node_modules/enzyme-adapter-utils/src/Utils.js:99:18)
      at Object.render (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:704:20)
      at new ShallowWrapper (node_modules/enzyme/src/ShallowWrapper.js:411:22)
      at Object.shallow (node_modules/enzyme/src/shallow.js:10:10)
      at Object.<anonymous> (src/components/Icons/Wallet/wallet.spec.tsx:9:27)
```

So, it seems that, for some reason, Enzyme can use `import * as React` but not `import React`. Any idea how to fix it? I can't rewrite all my components to use `import * as React`.

**Comment by ljharb** [comment]
enzyme has nothing to do with imports. You want `import React from ‘react’, and unless you enable synthetic imports and esModuleInterop, TS’ module system is broken.

It may also be your jest config. I’m happy to keep troubleshooting here, but I’m going to close this because it’s unrelated to enzyme.

**Comment by delucca** [comment]
I think it can be related to Jest thought, since `esModuleInterop` is already enabled in my tsconfig (outside of jest it works as expected)

**Comment by delucca** [comment]
Do you have any idea how to fix it in Jest? I'm using the following jest config: https://github.com/delucca/execution-mode/blob/chore/unit-tests/jest.config.ts

**Comment by delucca** [comment]
Just for future references, the issue was with my `tsconfig.json` file.

Althought I was already using both `allowSyntheticDefaultImports` and `esModuleInterop`, the `"jsx": "react"` config was missing.

Thanks in any case ;)
