### ISSUE TITLE
After upgrade React version 15 to 16.13.1 mount not working

### ISSUE THREAD

**Issue by psaravanan** [enzymejs/enzyme#2485]
### Getting below error when using "mount" but same is working fine when use "shallow"
```
TypeError: Right-hand side of 'instanceof' is not an object
      at getActiveElementDeep (node_modules\react-dom\cjs\react-dom.development.js:6941:18)
      at getSelectionInformation (node_modules\react-dom\cjs\react-dom.development.js:6972:21)
      at prepareForCommit (node_modules\react-dom\cjs\react-dom.development.js:7463:26)
      at commitRootImpl (node_modules\react-dom\cjs\react-dom.development.js:22474:5)
      at unstable_runWithPriority (node_modules\scheduler\cjs\scheduler.development.js:653:12)
      at runWithPriority$1 (node_modules\react-dom\cjs\react-dom.development.js:11039:10)
      at commitRoot (node_modules\react-dom\cjs\react-dom.development.js:22381:3)
      at finishSyncRender (node_modules\react-dom\cjs\react-dom.development.js:21807:3)
      at performSyncWorkOnRoot (node_modules\react-dom\cjs\react-dom.development.js:21793:7)
      at scheduleUpdateOnFiber (node_modules\react-dom\cjs\react-dom.development.js:21188:7)
      at updateContainer (node_modules\react-dom\cjs\react-dom.development.js:24373:3)
      at D:\Projects\my-reactr-project\node_modules\react-dom\cjs\react-dom.development.js:24758:7
      at unbatchedUpdates (node_modules\react-dom\cjs\react-dom.development.js:21903:12)
      at legacyRenderSubtreeIntoContainer (node_modules\react-dom\cjs\react-dom.development.js:24757:5)
      at Object.render (node_modules\react-dom\cjs\react-dom.development.js:24840:10)
      at getFiber (node_modules\enzyme-adapter-react-16\src\detectFiberTags.js:14:12)
      at detectFiberTags (node_modules\enzyme-adapter-react-16\src\detectFiberTags.js:76:15)
      at ReactSixteenAdapter.createMountRenderer (node_modules\enzyme-adapter-react-16\src\ReactSixteenAdapter.js:465:19)
      at ReactSixteenAdapter.createRenderer (node_modules\enzyme-adapter-react-16\src\ReactSixteenAdapter.js:820:51)
      at new ReactWrapper (node_modules\enzyme\src\ReactWrapper.js:113:32)
      at mount (node_modules\enzyme\src\mount.js:10:10)
      at Context.<anonymous> (test\unit\specs\ui\error_request\components/ErrorRequest.js:9:19)
```

 ### ErrorRequest.js
```jsx
    import React from 'react';
    export default class ErrorRequest extends React.Component {
      /* istanbul ignore next */
      constructor(props) {
        super(props);
      }

      render() {
          return (
              <div className='ErrorComponent'>
                  Test
              </div>
          );
      }
    }
```
### Config
```jsx
import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

configure({ adapter: new Adapter() });
import { JSDOM } from 'jsdom';
const { document } = (new JSDOM('<!doctype html><html><head>.....</html>')).window;
Object.assign(global,{toggleAccordion:function (){},carouselScroll:function(){}})
global.document = document;
global.SVGElement = Array;
global.window = {
...document,
  history: (same) => same,
.
.
.
}
```
### package.json
```json
"react": "16.13.1",
"react-dom": "16.13.1",
"enzyme": "^3.9.0",
"enzyme-adapter-react-16": "^1.13.2",
"mocha": "8.2.1",
"react-test-renderer": "^16.13.1",
"jsdom": "15.1.1",
"webpack": "4.42.1",
```

### package-lock.json
```json
"enzyme-adapter-react-16": {
      "version": "1.15.5",
      "resolved": "https://registry.npmjs.org/enzyme-adapter-react-16/-/enzyme-adapter-react-16-1.15.5.tgz",
      "integrity": "sha512-33yUJGT1nHFQlbVI5qdo5Pfqvu/h4qPwi1o0a6ZZsjpiqq92a3HjynDhwd1IeED+Su60HDWV8mxJqkTnLYdGkw==",
      "dev": true,
      "requires": {
        "enzyme-adapter-utils": "^1.13.1",
        "enzyme-shallow-equal": "^1.0.4",
        "has": "^1.0.3",
        "object.assign": "^4.1.0",
        "object.values": "^1.1.1",
        "prop-types": "^15.7.2",
        "react-is": "^16.13.1",
```

**Comment by ljharb** [comment]
In the future, please fill out the issue template exactly, and do not remove it - it's there for a reason.

You're using enzyme v3.9; can you try updating to v3.11?

(Separately, your constructor is redundant there and should be deleted)

I'll also need the *test code* that you're using.

**Comment by psaravanan** [comment]
> In the future, please fill out the issue template exactly, and do not remove it - it's there for a reason.
> sure.
> You're using enzyme v3.9; can you try updating to v3.11?
> Just tried and same output
> (Separately, your constructor is redundant there and should be deleted)
> sure
> I'll also need the _test code_ that you're using.

**Comment by psaravanan** [comment]
Please let me know what information needed, I will share that

**Comment by ljharb** [comment]
I still need the test code that you're using - the code that actually includes any use of enzyme with the ErrorRequest component.

**Comment by psaravanan** [comment]
Here is my Test case,
```
# My test case
import '../../util/common'; // where I configured 'jsdom'
import React from 'react';
import { expect } from 'chai';
import { mount } from 'enzyme';
import ErrorRequest from './ErrorRequest';

describe('error page components', () => {	
	it('error page component', () => {
		const wrapper = mount(<ErrorRequest />);
		expect(wrapper).to.have.length(1);
    });
});
```

**Comment by psaravanan** [comment]
I resolved the Issue.
In the file where "enzyme-adapter-react-16" and "jsdom" configured, I removed my custom assignment into the "window" object and issue disappeared then I changed the way of assigning value to "window" object,

```
# global.window = {
#   ...document,
#   history: (same) => same,
#   scrollTo: () => undefined,
#   split: () => undefined,
#   sort: () => undefined,
#   scroll: () => undefined,
#   addEventListener: (e, count) => { return {} },
#   sessionStorage: myMethod()
# }

global.window = document.defaultView;
global.window.scrollTo = () => undefined
global.window.split = () => undefined
global.window.sort = () => undefined
global.window.scroll = () => undefined
global.window.addEventListener = (e, count) => { return {} }
global.window.sessionStorage = myMethod()
```

**Comment by ljharb** [comment]
Indeed; you can't replace the entire window object or else it won't be a proper JSDOM window. Glad you figured it out!
