### ISSUE TITLE
Cannot find module 'cheerio' from 'node_modules/enzyme/build/Utils.js'

### ISSUE THREAD

**Issue by mmarshad** [enzymejs/enzyme#2518]
I just start receiving this message to my unit tests today, although it was working fine before

Cannot find module 'cheerio' from 'node_modules/enzyme/build/Utils.js'

    Require stack:
      node_modules/enzyme/build/Utils.js
      node_modules/enzyme/build/ShallowWrapper.js
      node_modules/enzyme-to-json/utils.js
      node_modules/enzyme-to-json/createSerializer.js
      node_modules/enzyme-to-json/serializer.js

      at Resolver.resolveModule (node_modules/jest-runtime/node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/enzyme/src/Utils.js:9:1)
Is there anything changed in serlizer.js?
"enzyme": "^3.11.0",
"enzyme-adapter-react-16": "^1.15.6",
"enzyme-to-json": "^3.6.1",

**Comment by ljharb** [comment]
`enzyme-to-json` is not maintained by the enzyme team, so you'd have to ask them.

**Comment by Mahdiyeh** [comment]
Same here for me:

` Cannot find module 'cheerio' from 'node_modules/enzyme/build/Utils.js'

    Require stack:
      node_modules/enzyme/build/Utils.js
      node_modules/enzyme/build/ReactWrapper.js
      node_modules/enzyme/build/index.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/enzyme/build/Utils.js:80:16)`
      
        "enzyme": "^3.11.0",
        "enzyme-adapter-react-16": "^1.15.5"

**Comment by ljharb** [comment]
Please try pinning cheerio to `=1.0.0.rc-3`, ensure it's installed, and let me know if the issue persists.

**Comment by rxgx** [comment]
Adding an override doesn't fix the issue with `enzyme` incorrectly using a loose RC pattern for a hard dependency.

```json
  "overrides": {
    "enzyme": {
      "cheerio": "1.0.0.rc-3"
    }
  },
```

**Comment by ljharb** [comment]
@rxgx while that should work - file an issue with npm if it doesn't - simply adding `"cheerio": "=1.0.0-rc-3"` to your `devDependencies` should be sufficient, no overrides required.

**Comment by rxgx** [comment]
@ljharb what old version of npm are you using?

```
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "=1.0.0.rc-3" of package "cheerio@=1.0.0.rc-3": Tags may not have any characters that encodeURIComponent encodes.
```

**Comment by ljharb** [comment]
works fine with every version of npm, through the latest. That's a version specifier, not a tag name.

**Comment by rxgx** [comment]
Is it possible that this version is missing from the registry? I get these errors even with `rm node_modules` and `npm cache verify`.

```
lerna notice cli v4.0.0
lerna ERR! cheerio: No matching version found for cheerio@1.0.0.rc-3.
lerna ERR!     at module.exports (/Users/rgasparini/Code/monorepo/node_modules/npm-pick-manifest/index.js:209:23)
lerna ERR! lerna No matching version found for cheerio@1.0.0.rc-3.
```

```
$ npm i -D cheerio@1.0.0.rc-3 
npm ERR! code ETARGET
npm ERR! notarget No matching version found for cheerio@1.0.0.rc-3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

```
$ npm i -D cheerio@=1.0.0.rc-3
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "=1.0.0.rc-3" of package "cheerio@=1.0.0.rc-3": Tags may not have any characters that encodeURIComponent encodes.
```

**Comment by ljharb** [comment]
Is it possible you're not using the public registry? It's quite there: https://unpkg.com/browse/cheerio@1.0.0-rc.3/

**Comment by rxgx** [comment]
Here's what I originally thought was the resolution before being derailed by the invalid `=` syntax. I got the hyphen and dots mixed up.

```
  "overrides": {
    "enzyme": {
      "cheerio": "1.0.0-rc.3"
    }
  },
```

**Comment by ljharb** [comment]
The = syntax is a range; overrides takes a specific version - it’s not invalid in general, i just wasn’t providing an override. Overrides should be used only as a last resort.

**Comment by nspector** [comment]
Looks like the change to pin it here: https://github.com/enzymejs/enzyme/commit/cafdb2b86ed8865527cdd6ae31c42593d3728ceb
was never published: https://unpkg.com/browse/enzyme@3.11.0/package.json. Can somebody publish it? Thank you!

**Comment by ljharb** [comment]
@nspector correct; it hasn't been published yet. it'll be in the next release.

Again, you can get the benefit now merely by doing `npm install --save-dev cheerio@=1.0.0-rc.3`.

**Comment by tonnyskk** [comment]
Try lock your cheerio version to `1.0.0-rc.10` E.g. by yarn resolutions. `1.0.0-rc.11` will throw the error.

**Comment by billnbell** [comment]
This worked for me
```
   "resolutions": {
+    "cheerio": "1.0.0-rc.10"
   },
```

**Comment by richard1230** [comment]
> This worked for me
> 
> ```
>    "resolutions": {
> +    "cheerio": "1.0.0-rc.10"
>    },
> ```

which file should it be put?

**Comment by billnbell** [comment]
Well devDependencies did not help. When I added "resolutions" it works.

**Comment by devinm-hrbl** [comment]
This has been a problem for an entire year? Is Enzyme a defunct library now?

**Comment by ljharb** [comment]
@devinm-hrbl no.

**Comment by bangnk** [comment]
I also have this issue. I am using Yarn with workspaces. Normally, after a `yarn install`, all dependencies are stored in node_modules in the root folder. My tests are inside a subfolder with its own `package.json`. 

So to hot fix the issue temporarily, I run `npm i` in the subfolder to install all dependencies AGAIN in node_modules in subfolder. I can delete everything in node_modules in subfolder except these three: enzyme, enzyme-adaptor-preact-pure, enzyme-to-json. Then all the tests pass again.

**Comment by s100** [comment]
@ljharb Is this package still actively maintained?

**Comment by ljharb** [comment]
@s100 yes, as you can see by my comment yesterday.

**Comment by s100** [comment]
> @s100 yes, as you can see by my comment yesterday.

Awesome... so, when can we expect a new release with this fix?

**Comment by ljharb** [comment]
@s100 i don't commit to specific release schedules, and the lack of a release is unrelated to whether the package is maintained.

**Comment by fengxinhhh** [comment]
Hello, I also found the error:
 Cannot find module 'cheerio/lib/utils' from 'node_modules/enzyme/build/Utils.js'

    Require stack:
      node_modules/enzyme/build/Utils.js
      node_modules/enzyme/build/ReactWrapper.js
      node_modules/enzyme/build/index.js
      src/__tests__/Button/button.test.tsx

My devDependencies list include enzyme are:

    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.2",
    "enzyme-to-json": "^3.3.5",

So, now we can't solve the problem?

**Comment by blixt** [comment]
I also ran into this issue and made this PR in the Cheerio repository:
https://github.com/cheeriojs/cheerio/pull/2601

Though since it's such a simple function (which could be replaced by `/<[a-zA-Z!][^>]*>/.test(str)`) that follows a spec and has no need of knowledge of behaviors within Cheerio, one could argue the better solution is to just embed it into Enzyme to avoid depending on the internal structure of another package.

**Comment by ljharb** [comment]
That’s a fair point. Cheerio could still be used to verify the results of the function in tests.

I’d be happy to accept a PR inlining that function.

**Comment by hesamhoseinkhani** [comment]
@ljharb any updates?

**Comment by kezzakyle** [comment]
This issue has shown up again. Jest testing with enzyme on react 17.
Error:
`Cannot find module 'cheerio/lib/utils' from 'node_modules/enzyme/build/Utils.js'

    Require stack:
      node_modules/enzyme/build/Utils.js
      node_modules/enzyme/build/ReactWrapper.js
      node_modules/enzyme/build/index.js

      1 | import React from "react";
    > 2 | import { configure, shallow } from "enzyme";`


package json:
` "resolutions": {
    "cheerio": "1.0.0"
  },
  "overrides": {
    "enzyme": {
      "cheerio": "1.0.0"
    }
  },`
  And also installed as dev dependent. Is it time to move to RTL? (React testing library)
